apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: notification-service
build:
  artifacts:
  - image: dthibau/notification-service
    context: .
    jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/notification.yaml
