apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: store-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: store
spec:
  hosts:
  - "*"
  gateways:
  - store-gateway
  http:
  - match:
    - uri:
        prefix: /order-service/
    rewrite:
      uri: /
    route:
    - destination:
        host: order-service

  - match:
    - uri:
        prefix: /delivery-service/
    rewrite:
      uri: /
    route:
    - destination:
        host: delivery-service
        subset: v1
      weight: 80
    - destination:
        host: delivery-service
        subset: v2
      weight: 20
        
  - match:
    - uri:
        prefix: /zipkin
    route:
    - destination:
        host: zipkin

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: delivery-service
spec:
  host: delivery-service
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
