spring:
  zipkin:
    base-url: http://zipkin:9411/
  sleuth: 
    sampler: 
      probability: 1  
      
management:
  endpoints:
    web:
      exposure:
        include:
        - env
        - beans
        - health
        - metrics
        - httptrace
        - refresh
        - gateway
  endpoint:
    health:
      show-details: always
    
---
spring:
  config:
    activate:
      on-profile:
      - kubernetes
  
  cloud:
    kubernetes:
      secrets:
        enabled: true
      reload:
        enabled: true
        mode: polling
        period: 5000    

