   
management:
  endpoints:
    web:
      exposure:
        include:
        - env
        - beans
        - health
        - metrics
        - httptrace
        - refresh
        - gateway
  endpoint:
    health:
      show-details: always
    
---
spring:
  config:
    activate:
      on-profile:
      - kubernetes
  
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000    

