apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      name: delivery-service
  template:
    metadata:
      labels:
        name: delivery-service
    spec:
      containers:
      - name: delivery-service
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name : MANAGEMENT_ENDPOINTS_HEALTH_PROBES_ENABLED
            value : 'true' 
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
          - name: POSTGRES_SERVICE
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_SERVICE
        image: dthibau/delivery-service:0.0.8
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 5
      imagePullSecrets:
        - name: regcred


  
--- 
kind: Service
apiVersion: v1
metadata:
  name: delivery-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    name: delivery-service
  type: NodePort
