apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
  - port: 8080
    targetPort: 9080
    name: http
  type: LoadBalancer
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification
        env :
          - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
            value: "/etc/secrets"
          - name: NOTIFICATION_USERNAME
            valueFrom:
              secretKeyRef:
                name: smtp-secret
                key: username
          - name: NOTIFICATION_PASSWORD
            valueFrom:
              secretKeyRef:
                name: smtp-secret
                key: password
        image: dthibau/notification-service
        volumeMounts:
          - name: secret
            mountPath: "/etc/secrets"
            readOnly: true
        ports:
          - containerPort: 9080
      - name: fake-smtp
        image: dthibau/fake-smtp:1.0
        ports:
          - containerPort: 2525
      volumes:
        - name: secret
          secret:
            secretName: smtp-secret
      

