apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service-v2
  labels:
    version: v2
spec:
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
        version: v2
    spec:
      containers:
      - name: delivery-service
        image: dthibau/delivery-service-kub:2.0.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
